version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  test_db:
    image: postgres
    volumes:
      - test-pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/url_shortener
    ports:
      - "3000:3000"
    depends_on:
      - db
  test:
    build: .
    volumes:
      - .:/url_shortener
    depends_on:
      - test_db
volumes:
  pg-data:
  test-pg-data:
